export enum AppType {
  PART = "PART",
  WEBCOMPONENT = "WEBCOMPONENT",
  IFRAME = "IFRAME",
  VUE = "VUE",
  ANGULAR = "ANGULAR",
  REACT = "REACT",
  JQUERY = "JQUERY",
  NATIVE = "NATIVE",
  OTHER = "OTHER",
}
